apiVersion: v1
kind: Service
metadata:
  name: sidecar-svc
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: sidecar
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar-deployment
  labels:
    app: sidecar
spec:
  selector:
    matchLabels:
      app: sidecar
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      name: sidecar-pod
      labels:
        app: sidecar
    spec:
      containers:
      - image:  hsjindoc/project_web
        name: fastapi-container
        ports:
        - containerPort: 8000


#https://wjdqlsdlsp.github.io/kubernetes/2022-07-03-k8s_network/